language: python
# sudo: false
os:
   - linux
python:
  - "2.7"
notifications:
  email: 
    on_failure: always
addons:
  apt:
    packages:
     - libblas-dev
     - liblapack-dev
     - gfortran
    # - libzmq3-dev
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
before_install:
  - pip install -U pip
install:
  - if [[ $TRAVIS_OS_NAME -eq "linux" ]]; then
      sudo apt-get update;
    fi
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - PY3K=$(echo "$TRAVIS_PYTHON_VERSION >= 3.0" | bc)
  - if [[ $TRAVIS_OS_NAME -eq "linux" ]]; then
      export MINICONDA_OS_NAME=Linux;
    elif [[ $TRAVIS_OS_NAME -eq "osx" ]]; then
      export MINICONDA_OS_NAME=MacOSX;
    fi
  - if [[ $PY3K -eq 1 ]]; then
      export MINICONDA_VERSION=3;
    else
      export MINICONDA_VERSION=;
    fi
  - wget https://repo.continuum.io/miniconda/Miniconda${MINICONDA_VERSION}-latest-${MINICONDA_OS_NAME}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n mosaicENV python=$TRAVIS_PYTHON_VERSION
  - source activate mosaicENV
  # Useful for debugging any issues with conda
  - conda info -a

  - conda install cython=0.20.1 pandas=0.16.2 nose=1.3.4 matplotlib=1.4.3 numpy=1.9.0 scipy=0.14.0 pyzmq=15.2.0
  - conda install -c ioos pywavelets=0.4.0
  - conda install -c licode lmfit=0.8.3
  - conda install -c ioos uncertainties=2.4.8
script: 
  - python setup.py mosaic_tests

