language: python
sudo: false
python:
  - "2.7"
notifications:
  email: false
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt --upgrade
script: 
  - nosetests -w mosaic/utest/ mosaicTests.py
