language: python
sudo: false
python:
  - "2.7"
notifications:
  email: 
    on_failure: always
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    #- libzmq3-dev
    - libqt4-dev
    - qt4-dev-tools 
    - python-qt4-dev 
    - pyqt4-dev-tools
    - python-qt4
    - python-docutils
    - sqlite3
before_install:
  - pip install docutils
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt --upgrade
  #- pip install pyzmq --upgrade
  - ln -s /usr/lib/python2.7/dist-packages/PyQt4/ $VIRTUAL_ENV/lib/python2.7/site-packages/
  - ln -s /usr/lib/python2.7/dist-packages/sip.so $VIRTUAL_ENV/lib/python2.7/site-packages/
script: 
  # - python setup.py test -madst
  - nosetests --with-coverage -v mosaic/tests/adept2State_Test.py mosaic/tests/adept_Test.py mosaic/tests/cusum_Test.py mosaic/tests/eventPartition_Test.py mosaic/tests/eventPartitionParallel_Test.py tests/dependencyVersion_Test.py mosaic/tests/import_Tests.py mosaic/tests/trajio_Test.py mosaicweb/tests/status_Test.py mosaicweb/tests/session_Test.py
  - codecov
