language: python
# sudo: false
python:
  - "2.7"
notifications:
  email: 
    on_failure: always
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - libzmq3-dev
    - libqt4-dev
    - qt4-dev-tools 
    - python-qt4-dev 
    - pyqt4-dev-tools
    - python-qt4
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt --upgrade
  - pip install pyzmq --upgrade
script: 
  - python setup.py mosaic_tests
